# -*- coding: utf-8 -*-
"""Копия 2.3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ckpt4Wdw_gzuF8bpy46rIZ-2QijoOxzY
"""

from math import factorial

print('Задание 1.')

def cards_1(n, k):
  return (k/n) * ((k-1)/(n-1)) * ((k-2)/(n-2)) * ((k-3)/(n-3))

print('Вероятность, что 4 выбранные карты - крести:', "{:.5f}".format(cards_1(52, 9)))

def cards_2(a, b, c):
  return (a/b) * c

print('Вероятность, что среди 4 карт будет не менее 1 туза:', "{:.5f}".format(cards_2(4, 52, 4)))

print('Задание 2.')

def code(n, k):
  return (factorial(n))/(factorial(k)*(factorial(n - k)))

print('Количество возможных комбинаций кода:', code(10, 3))
print(f'Вероятность угадать код с первого раза: 1:{code(10, 3)}')

print('Задание 3.')

def detail(n, k):
  return (k/n) * ((k-1)/(n-1)) * ((k-2)/(n-2))

print('Вероятность выбрать только окрашенные детали:', "{:.2f}".format(detail(15, 9)))

print('Задание 4.')

def lottery(n, k):
  return (k/n) * ((k-1)/(n-1))

print('Вероятность выиграть лотерею:', "{:.4f}".format(lottery(100, 2)))